### ISSUE TITLE
Create chooseQuiz component

### ISSUE THREAD

**Issue by MikaelEdwartz** [Blasipps-ganget/GeoQuizzer#24]

**Comment by MikaelEdwartz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Skapa komponent för att välja quiz på homepage](https://trello.com/c/qE1obDl0/39-skapa-komponent-f%C3%B6r-att-v%C3%A4lja-quiz-p%C3%A5-homepage)

**Comment by cchriss123** [comment]
fixed in other issue
